config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get                 'tos' => 'static_pages#tos'
  get                 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'tags/:tag', to: 'microposts#index', as: :tag
  resources :users do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :microposts, path: "excerpts", only: [:create, :show, :index, :new, :edit, :update, :destroy]
  resources :favorite_excerpts, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites
  has_many :favorite_excerpts, through: :favorites, source: :favorited, source_type: 'Micropost'
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 25 }, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  
  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:index, :destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    set_meta_tags :site => 'Amazing Metaphors - The Best Metaphors and Similes',
                  :publisher => 'https://plus.google.com/110072472091956031632',
                  :title => @user.name,
                  :nofollow => true,
                  :reverse => true
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorite_excerpts.paginate(page: params[:page])
    set_meta_tags :site => 'Amazing Metaphors - The Best Metaphors and Similes',
                  :publisher => 'https://plus.google.com/110072472091956031632',
                  :title => "#{@user.name}'s favorites",
                  :nofollow => true,
                  :reverse => true
  end
  
  def new
    @user = User.new
    set_meta_tags :site => 'Amazing Metaphors - The Best Metaphors and Similes',
                :publisher => 'https://plus.google.com/110072472091956031632',
                :title => 'Sign up'
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "WELCOME TO AMAZING METAPHORS!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    set_meta_tags :title => 'Edit Profile'
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
    set_meta_tags :title => @user.name,
                  :nofollow => true,
                  :reverse => true
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
    set_meta_tags :title => @user.name,
                  :nofollow => true,
                  :reverse => true
  end
  
  
  
    private

      def user_params
        params.require(:user).permit(:name, :email, :picture, :password,
                                     :password_confirmation)
      end
      
      # Confirms a logged-in user.
      def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end
      
      # Confirms the correct user.
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end
      
      # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<div class="center"><h1>Update your profile</h1></div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <hr>
      <%= f.label :password, 'Change password' %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm new password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <aside class="col-md-3 user-info-area">
    <section class="user_info">
      <%= image_tag @user.picture.url if @user.picture? %>
      <h1>
        <%= link_to @user.name, @user %>
      </h1>
    </section>
  </aside>
  <div class="col-md-9">
    <% if @user.favorites.any? %>
      <h3>Favorites</h3>
      <ol class="user-show-quotes lrg-quotes rmv-left-padding">
        <%= render @favorites %>
      </ol>
      <%= will_paginate @favorites %>
    <% else %>
      <h3><%= @user.name %> hasn't added any favorites yet</h3>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
     <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <span class="tos-link">by clicking "Create my account" you agree to our <%= link_to "terms of service", tos_path %></span>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-3 user-info-area">
    <section class="user_info">
      <%= image_tag @user.picture.url if @user.picture? %>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
    
    <!--keep out til more users-->
    <% if 1 == 0 %>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      </br>
    <% end %>
    

    <div><%= link_to "favorites", favorites_user_path(@user) %></div>

    
    <!--keep out til more users-->
    <% if 1 == 0 %>
      </br>
      <span class="follow-user-btn"><%= render 'follow_form' if logged_in? %></span>
    <% end %>
    
  </aside>
  <div class="col-md-9">
    <% if @user.microposts.any? %>
    <h3 class="center">submissions</h3>
      <ol class="user-show-quotes lrg-quotes rmv-left-padding">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% else %>
      <h3>no submissions</h3>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>