config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get                 'tos' => 'static_pages#tos'
  get                 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'tags/:tag', to: 'microposts#index', as: :tag
  resources :users do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :microposts, path: "excerpts", only: [:create, :show, :index, :new, :edit, :update, :destroy]
  resources :favorite_excerpts, only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<% unless logged_in? %>
  <h3 class="center guest-submit-header">submit as guest <small>or <%= link_to "sign up", signup_path %></small></h3>
<% end %>
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <div class="form-group">
      <%= f.label :content, 'Excerpt' %> <span style="color:red">*</span>
      <%= f.text_area :content, class: 'form-control excerpt-input' %>
    </div>
    <div class="form-group">
      <%= f.label :author %> <span style="color:red">*</span>
      <%= f.text_field :author, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :name_of_full_work, 'From' %>
      <%= f.text_field :name_of_full_work, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :year, 'Year published' %>
      <%= f.text_field :year, class: 'form-control' %>
    </div>
    <% if logged_in? %>
      <% if current_user.admin? %>
        <div class="form-group">
          <%= f.label :link_to_full_work, 'Link to full work' %>
          <%= f.text_field :link_to_full_work, class: 'form-control' %>
        </div>
      <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :tag_list, "Tags (separated by commas)" %>
      <%= f.text_field :tag_list, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :comparison_type, 'Comparison' %> <span style="color:red">*</span>
      <span class="glyphicon glyphicon-info-sign metaphor-info" data-toggle="popover" title="Metaphor vs Simile" data-content="A simile is a specific type of metaphor that uses 'like' or 'as' to make a comparison."></span>
      <%= f.select :comparison_type, ['Metaphor', 'Simile'], :prompt => "", class: 'form-control' %>
    </div>
    
  </div>
  <% unless logged_in? %>
    <span class="tos-link">by clicking "Submit" you agree to our <%= link_to "terms of service", tos_path %></span>
  <% end %>
  <div class="submit-excerpt-btn">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>