config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get                 'tos' => 'static_pages#tos'
  get                 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'tags/:tag', to: 'microposts#index', as: :tag
  resources :users do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :microposts, path: "excerpts", only: [:create, :show, :index, :new, :edit, :update, :destroy]
  resources :favorite_excerpts, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  has_many :favorites, as: :favorited
  has_many :fans, through: :favorites, source: :user
  acts_as_taggable
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { minimum: 9, maximum: 340 }
  validates :comparison_type, presence: true
  validates :author, presence: true, length: { minimum: 3, maximum: 40 }
  validates :name_of_full_work, length: { maximum: 100 }, allow_blank: true
  validates :link_to_full_work, length: { maximum: 200 }, allow_blank: true
  validates :year, length: { maximum: 4 }, allow_blank: true
  self.per_page = 10
  
  def slug
    author.downcase.gsub(" ", "-").gsub(".","")  
  end

  def to_param
    "#{id}-#{slug}"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:destroy, :update, :edit]
  before_action :correct_user,   only: :destroy
  def show
    @quote = Micropost.find(params[:id])
    @nextrandom = Micropost.offset(rand(Micropost.count)).first
    
    set_meta_tags :site => 'Amazing Metaphors - The Best Metaphors and Similes',
              :publisher => 'https://plus.google.com/110072472091956031632',
              :title => @quote.author,
              :description => "Quote from #{@quote.author} - #{@quote.content}",
              :keywords => "#{@quote.author}, #{@quote.content}, metaphor, simile, best metaphors, best similes, excerpt, quote, literature, art",
              :reverse => true,
              :og => {
              :site_name => 'Amazing Metaphors',
              :title    => "#{@quote.comparison_type} by #{@quote.author.upcase}",
              :description     => "#{@quote.content}",
              :url      => "https://amazingmetaphors.com#{view_context.url_for @quote}",
              :image    => "#{view_context.image_url('AMlogo.png')}"},
              :fb => {
                :app_id => '421096071401226'
              }
  end
  
  def index
    @q = Micropost.ransack(params[:q])
    @search = Micropost.search(params[:q])
    if params[:tag]
      @quotes = Micropost.tagged_with(params[:tag]).paginate(page: params[:page])
    elsif params[:metaphor]
      @quotes = Micropost.where(:comparison_type => 'Metaphor').paginate(page: params[:page])
    elsif params[:simile]
      @quotes = Micropost.where(:comparison_type => 'Simile').paginate(page: params[:page])
    else
      @quotes = @q.result(distinct: true).page(params[:page])
    end
    
    set_meta_tags :site => 'Amazing Metaphors - The Best Metaphors and Similes',
              :publisher => 'https://plus.google.com/110072472091956031632',
              :title => 'Excerpts',
              :description => "Excerpts of amazing metaphors and similes",
              :keywords => "metaphor, simile, best metaphors, best similes, excerpt, quote, literature, art",
              :reverse => true,
              :og => {
              :site_name => 'Amazing Metaphors',
              :title    => "Recently Added",
              :description     => "Our most recently added metaphors and similes.",
              :url      => 'https://www.amazingmetaphors.com/',
              :image    => "#{view_context.image_url('AMlogo.png')}"},
              :fb => {
                :app_id => '421096071401226'
              }
  end
  
  def create
    if logged_in?
      @micropost = current_user.microposts.build(micropost_params)
    else
      @micropost = User.where(:email => 'guest@amazingmetaphors.com').first.microposts.build(micropost_params)
    end
    if @micropost.save
      flash[:success] = "Submission successful!"
      redirect_to @micropost
    else
      render 'new'
    end
    set_meta_tags :noindex => true
  end
  
  def new
    @micropost = Micropost.new
    
    set_meta_tags :site => 'Amazing Metaphors - The Best Metaphors and Similes',
              :publisher => 'https://plus.google.com/110072472091956031632',
              :title => 'New Submission',
              :description => "Submit an amazing metaphor or simile",
              :keywords => "metaphor, simile, best metaphors, best similes, excerpt, quote, literature, art",
              :nofollow => true,
              :reverse => true
  end
  
  def edit
    set_meta_tags :noindex => true
    @micropost = Micropost.find(params[:id])
  end
  
  def update
    set_meta_tags :noindex => true
    @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      flash[:success] = "Successfully updated"
      redirect_to @micropost
    else
      render 'edit'
    end
  end

  def destroy
    set_meta_tags :noindex => true
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content, :comparison_type, :author, :name_of_full_work, :link_to_full_work, :year, :tag_list)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <p class="pquote"><%= micropost.content %></p>
  <div class="footnote">
    <%= micropost.author.upcase %> <%= 'in' if micropost.name_of_full_work? %> <cite title="Source Title">
      <% if micropost.link_to_full_work? %> 
        <a href='<%= micropost.link_to_full_work %>' target="_blank"><%= micropost.name_of_full_work %></a></cite>
      <% else %>
        <%= micropost.name_of_full_work %>
      <% end %>
    <span class="year"><%= micropost.year %></span>
  </div>
  <div class="timestamp">
    <% if micropost.tag_list.size > 0 %>
      <span class="tags-area">
        tags: <%= raw micropost.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </span>
    <% end %>
    <span class="user">
      <% if micropost.comparison_type == 'Metaphor' %>
        <%= link_to micropost.comparison_type.downcase, microposts_path(metaphor: true)  %>
      <% else %>
        <%= link_to micropost.comparison_type.downcase,  microposts_path(simile: true)  %>
      <% end %>
      <% if micropost.user.name != 'guest' %>
        posted by <%= link_to micropost.user.name, micropost.user %></span>
      <% end %>
    <% if logged_in? %>
      <div>
        <% unless current_user.favorite_excerpts.exists?(id: micropost.id) %>
          <%= link_to 'add to favorites', favorite_excerpts_path(micropost_id: micropost), class: "add-fav", method: :post, :remote => true %>
        <% else %>
          <%= link_to 'unfavorite', favorite_excerpt_path(micropost), method: :delete, class: "remove-fav", :remote => true %>
        <% end %>
      </div>
    <% end %>
    <% if current_user?(micropost.user) %>
      <div class='edit-delete-links'>
        <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_micropost_path(micropost) %>
        <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe, micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
      </div>
    <% end %>
    </br>
    <button class="share-btn" id="share-btn-micropost-<%= micropost.id %>"><span class="glyphicon glyphicon-share"></span></button>
    <div id="share-micropost-<%= micropost.id %>" class="share-buttons">
      <%= social_share_button_tag("#{micropost.content} - #{micropost.author}", :url => "https://www.amazingmetaphors.com#{url_for micropost}", 'data-twitter-title' => "#{micropost.content} - #{micropost.author} #amazingmetaphors", 'data-tumblr-title' => "#{micropost.content} - #{micropost.author}", :image => image_url('AMlogo.png'), :popup => "true", desc: "#{micropost.content} - #{micropost.author}") %>
    </div>
  </div>
  <script>
    $("#share-btn-micropost-<%= micropost.id %>").click(function() {
      $("#share-btn-micropost-<%= micropost.id %>").remove();
      $("#share-micropost-<%= micropost.id %>").fadeIn();
    });
  </script>
</li>

app/views/microposts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/micropost_form' %>
  </div>
</div>

app/views/microposts/index.html.erb
<div class="row">
  <div class="col-md-2">
    <div class="input-group search-area">
      <%= search_form_for @q do |f| %>
        <%= f.search_field :content_or_author_or_name_of_full_work_or_year_cont, class: 'form-control search-box', placeholder: 'search' %>
        <span class="input-group-btn">
          <button type="submit" class="btn btn-info">
              <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      <% end %>
    </div>
  </div>
  <div class="col-md-8 col-xs-12">
      <ul class="lrg-quotes rmv-left-padding">
        <%= render @quotes %>
      </ul>
  </div>
  <div class="col-md-2 col-xs-12 cloud-area">
    <span class='tags-title center'>popular tags</span>
    <div id="tag_cloud">
      <% tag_cloud Micropost.tag_counts, %w{s m l} do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      <% end %>
    </div>
  </div>
  <div class="col-md-offset-2 col-md-8 col-xs-12 center">
    <%= will_paginate @quotes, :inner_window => 1, :page_links => false %>
  </div>
</div>

app/views/microposts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/micropost_form' %>
  </div>
</div>
<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>

app/views/microposts/show.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2 col-xs-12">
        <ul class="lrg-quotes rmv-left-padding">
          <%= render @quote %>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 random-button">
        <%= link_to '<button type="button" class="btn btn-default">Generate <span class="glyphicon glyphicon-random"></span></button>'.html_safe, @nextrandom %>
    </div>
</div>