config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get                 'tos' => 'static_pages#tos'
  get                 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'tags/:tag', to: 'microposts#index', as: :tag
  resources :users do
    member do
      get :following, :followers, :favorites
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :microposts, path: "excerpts", only: [:create, :show, :index, :new, :edit, :update, :destroy]
  resources :favorite_excerpts, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <% if logged_in? %>
      <%= link_to "submit", new_micropost_path, 'data-no-turbolink' => true %> | <%= link_to "profile", current_user %> | <%= link_to "settings", edit_user_path(current_user), 'data-no-turbolink' => true %> | <%= link_to "log out", logout_path, method: "delete" %> | <%= link_to '<span class="glyphicon glyphicon-search"></span>'.html_safe, microposts_path %>
    <% else %>
      <%= link_to "submit", new_micropost_path, 'data-no-turbolink' => true %> | <%= link_to "log in", login_path, 'data-no-turbolink' => true %> | <%= link_to "sign up", signup_path, 'data-no-turbolink' => true %> | <%= link_to '<span class="glyphicon glyphicon-search footer-search-link"></span>'.html_safe, microposts_path %>
    <% end %>
  </small>
</footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60514120-2', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "AMAZING METAPHORS<span class='TM'>™</span>".html_safe, root_path, class: "navbar-brand" %>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1<%= ', maximum-scale=1, user-scalable=no' if params[:action] == 'new' || params[:action] == 'edit' %>">
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Imprima|Open+Sans' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><button type="button" class="close" data-dismiss="alert">&times;</button><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>